apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ .Release.Name }}-configmap'
  labels:
    {{- include "banyuhay.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
data:
  POSTGRESQL_USERNAME: "{{ .Values.postgresql.auth.username }}"
  POSTGRESQL_DATABASE: "{{ .Values.postgresql.auth.database }}"
  POSTGRESQL_HOST: "{{ .Release.Name }}-postgresql"
