apiVersion: v1
kind: Secret
metadata:
  name: '{{ .Release.Name }}-secrets'
  labels:
    {{- include "banyuhay.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation
    avp.kubernetes.io/path: kv/data/lab/banyuhay
stringData:
  {{- toYaml .Values.env | nindent 2 }}
