version: '3'

env:
  NAME: banyuhay

tasks:
  default:
    cmd:
      task: up

  up:
    desc: Build and start containers
    cmd: docker compose --project-name {{.NAME}} up --detach --build --remove-orphans

  stop:
    desc: Stop containers
    cmd: docker compose --project-name {{.NAME}} stop

  logs:
    desc: Follow logs
    cmd: docker compose --project-name {{.NAME}} logs --follow {{.CLI_ARGS}}

  restart:
    desc: Restart containers
    cmd: docker compose --project-name {{.NAME}} restart {{.CLI_ARGS}}

  down:
    desc: Stop and remove containers
    cmd: docker compose --project-name {{.NAME}} down

  clean:
    desc: Nuke everything
    cmd: docker compose --project-name {{.NAME}} down --volumes --remove-orphans

  exec:
    desc: Execute a command in a running container
    cmd: docker compose --project-name {{.NAME}} exec {{.CLI_ARGS}}

  generate-migration:
    desc: Generate a new migration revision file
    cmd: task exec -- api poetry run alembic revision -m '{{.CLI_ARGS}}'

  migrate:
    desc: Apply all migrations
    cmd: task exec -- api poetry run alembic upgrade head
