version: '3'

env:
  NAME: may-bidet-ba

tasks:
  default:
    cmd:
      task: up

  up:
    desc: Build and start containers
    cmds:
      - docker compose --project-name {{.NAME}} up --detach --build --remove-orphans

  stop:
    desc: Stop containers
    cmds:
      - docker compose --project-name {{.NAME}} stop

  logs:
    desc: Follow logs
    cmds:
      - docker compose --project-name {{.NAME}} logs --follow {{.CLI_ARGS}}

  restart:
    desc: Restart containers
    cmds:
      - docker compose --project-name {{.NAME}} restart {{.CLI_ARGS}}

  down:
    desc: Stop and remove containers
    cmds:
      - docker compose --project-name {{.NAME}} down

  clean:
    desc: Nuke everything
    cmds:
      - docker compose --project-name {{.NAME}} down --volumes --remove-orphans

  exec:
    desc: Execute a command in a running container
    cmds:
      - docker compose --project-name {{.NAME}} exec {{.CLI_ARGS}}
