repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: banyuhay
    namespace: banyuhay
    chart: ./banyuhay
    # set:
    #   - value: ref+vault://kv/lab/banyuhay#POSTGRESQL_PASSWORD
    #     name: apiEnv.POSTGRESQL_PASSWORD
    #   - value: ref+vault://kv/lab/banyuhay#SECRET_KEY
    #     name: apiEnv.SECRET_KEY
    #   - value: ref+vault://kv/lab/banyuhay#STYTCH_PROJECT_ID
    #     name: apiEnv.STYTCH_PROJECT_ID
    #   - value: ref+vault://kv/lab/banyuhay#STYTCH_SECRET
    #     name: apiEnv.STYTCH_SECRET
    #   - value: ref+vault://kv/lab/banyuhay#STYTCH_PUBLIC_TOKEN
    #     name: apiEnv.STYTCH_PUBLIC_TOKEN
    #   - value: ref+vault://kv/lab/banyuhay#STYTCH_PROJECT_ID
    #     name: appEnv.STYTCH_PROJECT_ID
    #   - value: ref+vault://kv/lab/banyuhay#STYTCH_SECRET
    #     name: appEnv.STYTCH_SECRET
    #   - value: ref+vault://kv/lab/banyuhay#STYTCH_PUBLIC_TOKEN
    #     name: appEnv.STYTCH_PUBLIC_TOKEN
