repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: banyuhay
    namespace: banyuhay
    chart: ./banyuhay
    set:
      - value: ref+vault://kv/lab/banyuhay#POSTGRESQL_PASSWORD
        name: env.POSTGRESQL_PASSWORD
